spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: weather
  cache:
    cache-names: weather
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:my-password}
      username: ${REDIS_USERNAME:default}
springdoc:
  swagger-ui:
    path: /
    disable-swagger-default-url: false
server:
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

api:
  base_url:
    visual_crossing: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
  key:
    visual_crossing: ${VISUAL_CROSSING_API_KEY}
